import 'package:flutter/material.dart';

class LocalizationManager extends ChangeNotifier {
  static final LocalizationManager _instance = LocalizationManager._internal();
  factory LocalizationManager() => _instance;

  LocalizationManager._internal();

  String _languageCode = 'tr';

  String get languageCode => _languageCode;

  final Map<String, String> _supportedLanguages = {
    'tr': 'Türkçe',
    'en': 'English',
    'de': 'Deutsch',
    'fr': 'Français',
    'it': 'Italiano',
    'es': 'Español',
    'zh': '中文 (Chinese)',
    'ru': 'Русский (Russian)',
    'ja': '日本語 (Japanese)',
    'ko': '한국어 (Korean)',
  };

  final Map<String, String> _languageFlags = {
    'tr': 'tr',
    'en': 'us', // or gb
    'de': 'de',
    'fr': 'fr',
    'it': 'it',
    'es': 'es',
    'zh': 'cn',
    'ru': 'ru',
    'ja': 'jp',
    'ko': 'kr',
  };

  Map<String, String> get supportedLanguages => _supportedLanguages;
  Map<String, String> get languageFlags => _languageFlags;

  void setLanguage(String code) {
    if (_supportedLanguages.containsKey(code)) {
      _languageCode = code;
      notifyListeners();
    }
  }

  String translate(String key, [Map<String, String>? params]) {
    String value = _localizedValues[_languageCode]?[key] ?? key;
    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': 'PROFESYONEL SES ANALİZİ',
      'start_analysis': 'ANALİZİ BAŞLAT',
      'record_book': 'KAYIT GÜNLÜĞÜ',
      'settings': 'Ayarlar',
      'select_language': 'Dil Seçimi',
      'voice_type_selection': 'SES TİPİ SEÇİMİ',
      'gender_prompt': 'Doğru analiz için lütfen cinsiyetinizi seçin:',
      'female': 'KADIN',
      'male': 'ERKEK',
      'analyzing': 'Analiz ediliyor...',
      'processing': 'İşleniyor...',
      'recording_started': 'Kayıt Başladı',
      'recording_stopped': 'Kayıt Durduruldu',
      'tap_to_record': 'Kaydı Başlatmak İçin Dokun',
      'tap_to_stop': 'Durdurmak İçin Dokun',
      'analysis_result': 'Analiz Sonucu',
      'avg_pitch': 'Ortalama Pitch',
      'max_pitch': 'Maksimum Pitch',
      'min_pitch': 'Minimum Pitch',
      'voice_type': 'Ses Tipi',
      'no_recordings_yet': 'Henüz kayıt yok.',
      'rename': 'Adlandır',
      'delete': 'Sil',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'rename_recording_title': 'Yeniden Adlandır',
      'new_file_name_hint': 'Yeni dosya adı',
      'recording_name_updated': 'Kayıt adı güncellendi',
      'delete_recording_title': 'Kayıt Sil',
      'delete_recording_confirmation': '{filename} adlı kaydı silmek istiyor musunuz?',
      'recording_deleted': 'Kayıt silindi',
      'error': 'Hata',
      'connection_error': 'Bağlantı hatası',
      'pitch_analysis': 'SES ANALİZİ',
      'your_voice_type': 'SES TİPİNİZ',
      'frequency': 'FREKANS',
      'duration': 'SÜRE',
      'detailed_analysis': 'DETAYLI ANALİZ',
      'note_range': 'NOTA ARALIĞI',
      'frequency_range': 'FREKANS ARALIĞI',
      'pitch_progression': 'PITCH İLERLEMESİ',
      'no_data': 'Veri yok',
      'voice_soprano': 'SOPRANO',
      'voice_mezzo_soprano': 'MEZZO SOPRANO',
      'voice_contralto': 'KONTRALTO',
      'voice_counter_tenor': 'KONTRTENÖR',
      'voice_tenor': 'TENÖR',
      'voice_baritone': 'BARİTON',
      'voice_bass': 'BAS',
      'voice_unknown': 'BİLİNMEYEN',
    },
    'en': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': 'PROFESSIONAL PITCH ANALYSIS',
      'start_analysis': 'START THE ANALYSIS',
      'record_book': 'RECORD BOOK',
      'settings': 'Settings',
      'select_language': 'Select Language',
      'voice_type_selection': 'VOICE TYPE SELECTION',
      'gender_prompt': 'For accurate analysis, please select your gender:',
      'female': 'FEMALE',
      'male': 'MALE',
      'analyzing': 'Being analysed...',
      'processing': 'Processing...',
      'recording_started': 'Recording Started',
      'recording_stopped': 'Recording Stopped',
      'tap_to_record': 'Tap to Start Recording',
      'tap_to_stop': 'Tap to Stop',
      'analysis_result': 'Analysis Result',
      'avg_pitch': 'Average Pitch',
      'max_pitch': 'Max Pitch',
      'min_pitch': 'Min Pitch',
      'voice_type': 'Voice Type',
      'no_recordings_yet': 'No recordings yet.',
      'rename': 'Rename',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'save': 'Save',
      'rename_recording_title': 'Rename Recording',
      'new_file_name_hint': 'New file name',
      'recording_name_updated': 'Recording name updated',
      'delete_recording_title': 'Delete Recording',
      'delete_recording_confirmation': 'Do you want to delete {filename}?',
      'recording_deleted': 'Recording deleted',
      'error': 'Error',
      'connection_error': 'Connection error',
      'pitch_analysis': 'PITCH ANALYSIS',
      'your_voice_type': 'YOUR VOICE TYPE',
      'frequency': 'FREQUENCY',
      'duration': 'DURATION',
      'detailed_analysis': 'DETAILED ANALYSIS',
      'note_range': 'NOTE RANGE',
      'frequency_range': 'FREQUENCY RANGE',
      'pitch_progression': 'PITCH PROGRESSION',
      'no_data': 'No data',
      'voice_soprano': 'SOPRANO',
      'voice_mezzo_soprano': 'MEZZO SOPRANO',
      'voice_contralto': 'CONTRALTO',
      'voice_counter_tenor': 'COUNTER TENOR',
      'voice_tenor': 'TENOR',
      'voice_baritone': 'BARITONE',
      'voice_bass': 'BASS',
      'voice_unknown': 'UNKNOWN',
    },
    'de': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': 'PROFESSIONELLE TONANALYSE',
      'start_analysis': 'ANALYSE STARTEN',
      'record_book': 'AUFNAHMELISTE',
      'settings': 'Einstellungen',
      'select_language': 'Sprache auswählen',
      'voice_type_selection': 'STIMMTYP AUSWAHL',
      'gender_prompt': 'Für eine genaue Analyse wählen Sie bitte Ihr Geschlecht:',
      'female': 'WEIBLICH',
      'male': 'MÄNNLICH',
      'analyzing': 'Wird analysiert...',
      'processing': 'Verarbeitung...',
      'recording_started': 'Aufnahme gestartet',
      'recording_stopped': 'Aufnahme gestoppt',
      'tap_to_record': 'Tippen zum Starten',
      'tap_to_stop': 'Tippen zum Stoppen',
      'analysis_result': 'Analyseergebnis',
      'avg_pitch': 'Durchschn. Tonhöhe',
      'max_pitch': 'Max. Tonhöhe',
      'min_pitch': 'Min. Tonhöhe',
      'voice_type': 'Stimmlage',
      'no_recordings_yet': 'Noch keine Aufnahmen.',
      'rename': 'Umbenennen',
      'delete': 'Löschen',
      'cancel': 'Abbrechen',
      'save': 'Speichern',
      'rename_recording_title': 'Aufnahme umbenennen',
      'new_file_name_hint': 'Neuer Dateiname',
      'recording_name_updated': 'Aufnahme umbenannt',
      'delete_recording_title': 'Aufnahme löschen',
      'delete_recording_confirmation': 'Möchten Sie {filename} löschen?',
      'recording_deleted': 'Aufnahme gelöscht',
      'error': 'Fehler',
      'connection_error': 'Verbindungsfehler',
      'pitch_analysis': 'TONANALYSE',
      'your_voice_type': 'IHRE STIMMLAGE',
      'frequency': 'FREQUENZ',
      'duration': 'DAUER',
      'detailed_analysis': 'DETAILLIERTE ANALYSE',
      'note_range': 'NOTENBEREICH',
      'frequency_range': 'FREQUENZBEREICH',
      'pitch_progression': 'TONHÖHENVERLAUF',
      'no_data': 'Keine Daten',
      'voice_soprano': 'SOPRAN',
      'voice_mezzo_soprano': 'MEZZO-SOPRAN',
      'voice_contralto': 'ALT',
      'voice_counter_tenor': 'COUNTERTENOR',
      'voice_tenor': 'TENOR',
      'voice_baritone': 'BARITON',
      'voice_bass': 'BASS',
      'voice_unknown': 'UNBEKANNT',
    },
    'fr': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': 'ANALYSE VOCALE PROFESSIONNELLE',
      'start_analysis': 'LANCER L\'ANALYSE',
      'record_book': 'REGISTRE',
      'settings': 'Paramètres',
      'select_language': 'Choisir la langue',
      'voice_type_selection': 'SÉLECTION TYPE DE VOIX',
      'gender_prompt': 'Pour une analyse précise, veuillez sélectionner votre sexe :',
      'female': 'FEMME',
      'male': 'HOMME',
      'analyzing': 'Analyse en cours...',
      'processing': 'Traitement...',
      'recording_started': 'Enregistrement démarré',
      'recording_stopped': 'Enregistrement arrêté',
      'tap_to_record': 'Appuyez pour enregistrer',
      'tap_to_stop': 'Appuyez pour arrêter',
      'analysis_result': 'Résultat de l\'analyse',
      'avg_pitch': 'Hauteur Moyenne',
      'max_pitch': 'Hauteur Max',
      'min_pitch': 'Hauteur Min',
      'voice_type': 'Type de Voix',
      'no_recordings_yet': 'Aucun enregistrement.',
      'rename': 'Renommer',
      'delete': 'Supprimer',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'rename_recording_title': 'Renommer l\'enregistrement',
      'new_file_name_hint': 'Nouveau nom de fichier',
      'recording_name_updated': 'Nom mis à jour',
      'delete_recording_title': 'Supprimer l\'enregistrement',
      'delete_recording_confirmation': 'Voulez-vous supprimer {filename} ?',
      'recording_deleted': 'Enregistrement supprimé',
      'error': 'Erreur',
      'connection_error': 'Erreur de connexion',
      'pitch_analysis': 'ANALYSE VOCALE',
      'your_voice_type': 'VOTRE TYPE DE VOIX',
      'frequency': 'FRÉQUENCE',
      'duration': 'DURÉE',
      'detailed_analysis': 'ANALYSE DÉTAILLÉE',
      'note_range': 'GAMME DE NOTES',
      'frequency_range': 'GAMME DE FRÉQUENCES',
      'pitch_progression': 'PROGRESSION DE HAUTEUR',
      'no_data': 'Pas de données',
      'voice_soprano': 'SOPRANO',
      'voice_mezzo_soprano': 'MEZZO-SOPRANO',
      'voice_contralto': 'CONTRALTO',
      'voice_counter_tenor': 'CONTRE-TÉNOR',
      'voice_tenor': 'TÉNOR',
      'voice_baritone': 'BARYTON',
      'voice_bass': 'BASSE',
      'voice_unknown': 'INCONNU',
    },
    'it': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': 'ANALISI VOCALE PROFESSIONALE',
      'start_analysis': 'AVVIA ANALISI',
      'record_book': 'REGISTRO',
      'settings': 'Impostazioni',
      'select_language': 'Seleziona Lingua',
      'voice_type_selection': 'SELEZIONE TIPO VOCE',
      'gender_prompt': 'Per un\'analisi accurata, seleziona il tuo genere:',
      'female': 'DONNA',
      'male': 'UOMO',
      'analyzing': 'In analisi...',
      'processing': 'Elaborazione...',
      'recording_started': 'Registrazione avviata',
      'recording_stopped': 'Registrazione fermata',
      'tap_to_record': 'Tocca per registrare',
      'tap_to_stop': 'Tocca per fermare',
      'analysis_result': 'Risultato Analisi',
      'avg_pitch': 'Tonalità Media',
      'max_pitch': 'Tonalità Max',
      'min_pitch': 'Tonalità Min',
      'voice_type': 'Tipo di Voce',
      'no_recordings_yet': 'Nessuna registrazione.',
      'rename': 'Rinomina',
      'delete': 'Elimina',
      'cancel': 'Annulla',
      'save': 'Salva',
      'rename_recording_title': 'Rinomina Registrazione',
      'new_file_name_hint': 'Nuovo nome file',
      'recording_name_updated': 'Nome aggiornato',
      'delete_recording_title': 'Elimina Registrazione',
      'delete_recording_confirmation': 'Vuoi eliminare {filename}?',
      'recording_deleted': 'Registrazione eliminata',
      'error': 'Errore',
      'connection_error': 'Errore di connessione',
      'pitch_analysis': 'ANALISI TONALE',
      'your_voice_type': 'IL TUO TIPO DI VOCE',
      'frequency': 'FREQUENZA',
      'duration': 'DURATA',
      'detailed_analysis': 'ANALISI DETTAGLIATA',
      'note_range': 'GAMMA DI NOTE',
      'frequency_range': 'GAMMA DI FREQUENZA',
      'pitch_progression': 'PROGRESSIONE TONALE',
      'no_data': 'Nessun dato',
      'voice_soprano': 'SOPRANO',
      'voice_mezzo_soprano': 'MEZZO SOPRANO',
      'voice_contralto': 'CONTRALTO',
      'voice_counter_tenor': 'CONTROTENORE',
      'voice_tenor': 'TENORE',
      'voice_baritone': 'BARITONO',
      'voice_bass': 'BASSO',
      'voice_unknown': 'SCONOSCIUTO',
    },
    'es': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': 'ANÁLISIS VOCAL PROFESIONAL',
      'start_analysis': 'INICIAR ANÁLISIS',
      'record_book': 'REGISTRO',
      'settings': 'Ajustes',
      'select_language': 'Seleccionar Idioma',
      'voice_type_selection': 'SELECCIÓN TIPO DE VOZ',
      'gender_prompt': 'Para un análisis preciso, seleccione su género:',
      'female': 'MUJER',
      'male': 'HOMBRE',
      'analyzing': 'Analizando...',
      'processing': 'Procesando...',
      'recording_started': 'Grabación iniciada',
      'recording_stopped': 'Grabación detenida',
      'tap_to_record': 'Toque para grabar',
      'tap_to_stop': 'Toque para detener',
      'analysis_result': 'Resultado del Análisis',
      'avg_pitch': 'Tono Promedio',
      'max_pitch': 'Tono Máx',
      'min_pitch': 'Tono Mín',
      'voice_type': 'Tipo de Voz',
      'no_recordings_yet': 'No hay grabaciones.',
      'rename': 'Renombrar',
      'delete': 'Eliminar',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'rename_recording_title': 'Renombrar Grabación',
      'new_file_name_hint': 'Nuevo nombre de archivo',
      'recording_name_updated': 'Nombre actualizado',
      'delete_recording_title': 'Eliminar Grabación',
      'delete_recording_confirmation': '¿Desea eliminar {filename}?',
      'recording_deleted': 'Grabación eliminada',
      'error': 'Error',
      'connection_error': 'Error de conexión',
      'pitch_analysis': 'ANÁLISIS DE TONO',
      'your_voice_type': 'TU TIPO DE VOZ',
      'frequency': 'FRECUENCIA',
      'duration': 'DURACIÓN',
      'detailed_analysis': 'ANÁLISIS DETALLADO',
      'note_range': 'RANGO DE NOTAS',
      'frequency_range': 'RANGO DE FRECUENCIA',
      'pitch_progression': 'PROGRESIÓN DE TONO',
      'no_data': 'Sin datos',
      'voice_soprano': 'SOPRANO',
      'voice_mezzo_soprano': 'MEZZO-SOPRANO',
      'voice_contralto': 'CONTRALTO',
      'voice_counter_tenor': 'CONTRATENOR',
      'voice_tenor': 'TENOR',
      'voice_baritone': 'BARÍTONO',
      'voice_bass': 'BAJO',
      'voice_unknown': 'DESCONOCIDO',
    },
    'zh': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': '专业音高分析',
      'start_analysis': '开始分析',
      'record_book': '录音记录',
      'settings': '设置',
      'select_language': '选择语言',
      'voice_type_selection': '声音类型选择',
      'gender_prompt': '为了准确分析，请选择您的性别：',
      'female': '女性',
      'male': '男性',
      'analyzing': '正在分析...',
      'processing': '处理中...',
      'recording_started': '开始录音',
      'recording_stopped': '停止录音',
      'tap_to_record': '点击开始录音',
      'tap_to_stop': '点击停止',
      'analysis_result': '分析结果',
      'avg_pitch': '平均音高',
      'max_pitch': '最高音高',
      'min_pitch': '最低音高',
      'voice_type': '声音类型',
      'no_recordings_yet': '暂无录音',
      'rename': '重命名',
      'delete': '删除',
      'cancel': '取消',
      'save': '保存',
      'rename_recording_title': '重命名录音',
      'new_file_name_hint': '新文件名',
      'recording_name_updated': '录音名称已更新',
      'delete_recording_title': '删除录音',
      'delete_recording_confirmation': '您确定要删除 {filename} 吗？',
      'recording_deleted': '录音已删除',
      'error': '错误',
      'connection_error': '连接错误',
      'pitch_analysis': '音高分析',
      'your_voice_type': '您的声音类型',
      'frequency': '频率',
      'duration': '时长',
      'detailed_analysis': '详细分析',
      'note_range': '音域范围',
      'frequency_range': '频率范围',
      'pitch_progression': '音高变化',
      'no_data': '无数据',
      'voice_soprano': '女高音',
      'voice_mezzo_soprano': '女中音',
      'voice_contralto': '女低音',
      'voice_counter_tenor': '假声男高音',
      'voice_tenor': '男高音',
      'voice_baritone': '男中音',
      'voice_bass': '男低音',
      'voice_unknown': '未知',
    },
    'ru': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': 'ПРОФЕССИОНАЛЬНЫЙ АНАЛИЗ',
      'start_analysis': 'НАЧАТЬ АНАЛИЗ',
      'record_book': 'ЖУРНАЛ ЗАПИСЕЙ',
      'settings': 'Настройки',
      'select_language': 'Выберите язык',
      'voice_type_selection': 'ВЫБОР ТИПА ГОЛОСА',
      'gender_prompt': 'Для точного анализа выберите ваш пол:',
      'female': 'ЖЕНЩИНА',
      'male': 'МУЖЧИНА',
      'analyzing': 'Анализ...',
      'processing': 'Обработка...',
      'recording_started': 'Запись началась',
      'recording_stopped': 'Запись остановлена',
      'tap_to_record': 'Нажмите для записи',
      'tap_to_stop': 'Нажмите для остановки',
      'analysis_result': 'Результат анализа',
      'avg_pitch': 'Средний тон',
      'max_pitch': 'Макс. тон',
      'min_pitch': 'Мин. тон',
      'voice_type': 'Тип голоса',
      'no_recordings_yet': 'Записей пока нет.',
      'rename': 'Переименовать',
      'delete': 'Удалить',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'rename_recording_title': 'Переименовать запись',
      'new_file_name_hint': 'Новое имя файла',
      'recording_name_updated': 'Имя записи обновлено',
      'delete_recording_title': 'Удалить запись',
      'delete_recording_confirmation': 'Вы хотите удалить {filename}?',
      'recording_deleted': 'Запись удалена',
      'error': 'Ошибка',
      'connection_error': 'Ошибка соединения',
      'pitch_analysis': 'АНАЛИЗ ВЫСОТЫ ТОНА',
      'your_voice_type': 'ВАШ ТИП ГОЛОСА',
      'frequency': 'ЧАСТОТА',
      'duration': 'ДЛИТЕЛЬНОСТЬ',
      'detailed_analysis': 'ПОДРОБНЫЙ АНАЛИЗ',
      'note_range': 'ДИАПАЗОН НОТ',
      'frequency_range': 'ДИАПАЗОН ЧАСТОТ',
      'pitch_progression': 'ДИНАМИКА ТОНА',
      'no_data': 'Нет данных',
      'voice_soprano': 'СОПРАНО',
      'voice_mezzo_soprano': 'МЕЦЦО-СОПРАНО',
      'voice_contralto': 'КОНТРАЛЬТО',
      'voice_counter_tenor': 'КОНТРТЕНОР',
      'voice_tenor': 'ТЕНОР',
      'voice_baritone': 'БАРИТОН',
      'voice_bass': 'БАС',
      'voice_unknown': 'НЕИЗВЕСТНО',
    },
    'ja': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': 'プロフェッショナルピッチ分析',
      'start_analysis': '分析を開始',
      'record_book': '録音記録',
      'settings': '設定',
      'select_language': '言語を選択',
      'voice_type_selection': '声の種類を選択',
      'gender_prompt': '正確な分析のために性別を選択してください：',
      'female': '女性',
      'male': '男性',
      'analyzing': '分析中...',
      'processing': '処理中...',
      'recording_started': '録音開始',
      'recording_stopped': '録音停止',
      'tap_to_record': 'タップして録音開始',
      'tap_to_stop': 'タップして停止',
      'analysis_result': '分析結果',
      'avg_pitch': '平均ピッチ',
      'max_pitch': '最大ピッチ',
      'min_pitch': '最小ピッチ',
      'voice_type': '声のタイプ',
      'no_recordings_yet': '録音はまだありません。',
      'rename': '名前変更',
      'delete': '削除',
      'cancel': 'キャンセル',
      'save': '保存',
      'rename_recording_title': '録音名の変更',
      'new_file_name_hint': '新しいファイル名',
      'recording_name_updated': '録音名が更新されました',
      'delete_recording_title': '録音の削除',
      'delete_recording_confirmation': '{filename} を削除しますか？',
      'recording_deleted': '録音が削除されました',
      'error': 'エラー',
      'connection_error': '接続エラー',
      'pitch_analysis': 'ピッチ分析',
      'your_voice_type': 'あなたの声のタイプ',
      'frequency': '周波数',
      'duration': '期間',
      'detailed_analysis': '詳細分析',
      'note_range': '音域',
      'frequency_range': '周波数範囲',
      'pitch_progression': 'ピッチ推移',
      'no_data': 'データなし',
      'voice_soprano': 'ソプラノ',
      'voice_mezzo_soprano': 'メゾソプラノ',
      'voice_contralto': 'コントラルト',
      'voice_counter_tenor': 'カウンターテナー',
      'voice_tenor': 'テノール',
      'voice_baritone': 'バリトン',
      'voice_bass': 'バス',
      'voice_unknown': '不明',
    },
    'ko': {
      'app_title': 'VOCAL STUDIO',
      'subtitle': '전문 피치 분석',
      'start_analysis': '분석 시작',
      'record_book': '녹음 기록',
      'settings': '설정',
      'select_language': '언어 선택',
      'voice_type_selection': '음성 유형 선택',
      'gender_prompt': '정확한 분석을 위해 성별을 선택하세요:',
      'female': '여성',
      'male': '남성',
      'analyzing': '분석 중...',
      'processing': '처리 중...',
      'recording_started': '녹음 시작됨',
      'recording_stopped': '녹음 중지됨',
      'tap_to_record': '녹음 시작하려면 탭',
      'tap_to_stop': '중지하려면 탭',
      'analysis_result': '분석 결과',
      'avg_pitch': '평균 피치',
      'max_pitch': '최대 피치',
      'min_pitch': '최소 피치',
      'voice_type': '음성 유형',
      'no_recordings_yet': '녹음 없음.',
      'rename': '이름 변경',
      'delete': '삭제',
      'cancel': '취소',
      'save': '저장',
      'rename_recording_title': '녹음 이름 변경',
      'new_file_name_hint': '새 파일 이름',
      'recording_name_updated': '녹음 이름 업데이트됨',
      'delete_recording_title': '녹음 삭제',
      'delete_recording_confirmation': '{filename} 파일을 삭제하시겠습니까?',
      'recording_deleted': '녹음 삭제됨',
      'error': '오류',
      'connection_error': '연결 오류',
      'pitch_analysis': '피치 분석',
      'your_voice_type': '당신의 음성 유형',
      'frequency': '주파수',
      'duration': '재생 시간',
      'detailed_analysis': '상세 분석',
      'note_range': '음역',
      'frequency_range': '주파수 범위',
      'pitch_progression': '피치 진행',
      'no_data': '데이터 없음',
      'voice_soprano': '소프라노',
      'voice_mezzo_soprano': '메조소프라노',
      'voice_contralto': '콘트랄토',
      'voice_counter_tenor': '카운터테너',
      'voice_tenor': '테너',
      'voice_baritone': '바리톤',
      'voice_bass': '베이스',
      'voice_unknown': '알 수 없음',
    },
  };
}
